use std::env;
use std::path::PathBuf;

fn main() {
    let target_arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap();

    // Do nothing for WASM builds
    if target_arch == "wasm32" {
        return;
    }

    generate_c_header();
    generate_windows_resources();
}

fn generate_c_header() {
    use cbindgen::{Config, EnumConfig, Language};

    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let package_name = env::var("CARGO_PKG_NAME").unwrap();

    let output_file = target_dir()
        .join(format!("{}.h", package_name));

    let config = Config {
        autogen_warning: Some("// Autogenerated header file".into()),
        namespace: Some("ffi".into()),
        language: Language::C,
        include_version: true,
        package_version: true,
        pragma_once: true,
        enumeration: EnumConfig {
            prefix_with_name: true,
            ..Default::default()
        },
        ..Default::default()
    };

    cbindgen::generate_with_config(crate_dir, config)
        .expect("cbindgen failed")
        .write_to_file(output_file);
}

#[cfg(windows)]
fn generate_windows_resources() {
    // Also skip if target is wasm
    if std::env::var("CARGO_CFG_TARGET_ARCH").unwrap() == "wasm32" {
        return;
    }

    let mut res = winres::WindowsResource::new();

    if let Some(version) = retrieve_app_version_from_git_repository() {
        res.set("ProductVersion", &version);
    }

    res.compile().unwrap();
}

#[cfg(not(windows))]
fn generate_windows_resources() {}

fn target_dir() -> PathBuf {
    if let Ok(target) = env::var("CARGO_TARGET_DIR") {
        PathBuf::from(target)
    } else {
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap()).join("target")
    }
}

fn retrieve_app_version_from_git_repository() -> Option<String> {
    std::process::Command::new("git")
        .args(["describe", "--tags", "--dirty"])
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_owned())
}
